USE [C:\DEV\VS\MVCA\APP_DATA\MVCA.MDF]
GO

/****** Object: Table [dbo].[People] Script Date: 8/13/2019 9:07:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[People] (
    [Id]          INT          NOT NULL,
    [name]        VARCHAR (20) NULL,
    [create_date] DATETIME     NULL,
    [comment]     VARCHAR (50) NULL,
 CONSTRAINT [PK_People_3214EC07F952392B] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


